# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import nibabel as nb
from os import listdir
import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from show2D import Thread_1,Thread_2
import matplotlib
matplotlib.use('TkAgg')
from nibabel.viewers import OrthoSlicer3D
from PyQt5.QtWidgets import QFileDialog, QMainWindow
import nibabel as nib
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 21, 731, 61))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 211, 41))
        self.pushButton.setStyleSheet("font: 14pt \"Agency FB\";")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 90, 491, 41))
        self.textBrowser.setStyleSheet("font: 14pt \"Arial Unicode MS\";")
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 741, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 170, 121, 41))
        self.pushButton_2.setStyleSheet("font: 12pt \"Agency FB\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 270, 81, 41))
        self.pushButton_3.setStyleSheet("font: 12pt \"Agency FB\";\n"
"background-color: rgb(32, 255, 20);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 230, 741, 31))
        self.label_2.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 270, 111, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 270, 121, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 270, 54, 31))
        self.label_3.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 140, 741, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 270, 54, 31))
        self.label_4.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 220, 741, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(260, 170, 461, 41))
        self.textBrowser_2.setStyleSheet("font: 14pt \"Arial Unicode MS\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 370, 121, 41))
        self.pushButton_4.setStyleSheet("font: 12pt \"Agency FB\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(140, 370, 331, 91))
        self.textBrowser_3.setStyleSheet("font: 20pt \"Arial Unicode MS\";")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 330, 741, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 410, 121, 51))
        self.pushButton_5.setStyleSheet("font: 12pt \"Agency FB\";\n"
"background-color: rgb(85, 170, 255);\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 420, 121, 41))
        self.pushButton_6.setStyleSheet("font: 12pt \"Agency FB\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 460, 741, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(560, 350, 121, 41))
        self.pushButton_7.setStyleSheet("font: 12pt \"Agency FB\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(60, 520, 651, 41))
        self.textBrowser_4.setStyleSheet("font: 14pt \"Arial Unicode MS\";\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 520, 54, 31))
        self.label_5.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 170, 91, 31))
        self.label_6.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 470, 741, 31))
        self.label_7.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 580, 41, 31))
        self.label_8.setStyleSheet("font: 14pt \"Agency FB\";\n"
"font: 12pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(50, 580, 151, 41))
        self.textBrowser_5.setStyleSheet("font: 14pt \"Arial Unicode MS\";")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 580, 41, 31))
        self.label_9.setStyleSheet("font: 14pt \"Agency FB\";\n"
"font: 12pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(510, 580, 41, 31))
        self.label_10.setStyleSheet("font: 14pt \"Agency FB\";\n"
"font: 12pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 650, 141, 31))
        self.label_11.setStyleSheet("font: 14pt \"Agency FB\";\n"
"font: 12pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(400, 650, 41, 31))
        self.label_12.setStyleSheet("font: 14pt \"Agency FB\";\n"
"font: 12pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 560, 741, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 630, 741, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(230, 570, 16, 71))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(490, 570, 16, 71))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(0, 0, 741, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(0, 700, 741, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(730, 10, 20, 711))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(340, 640, 16, 71))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(300, 580, 161, 41))
        self.textBrowser_6.setStyleSheet("font: 14pt \"Arial Unicode MS\";")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(550, 580, 161, 41))
        self.textBrowser_7.setStyleSheet("font: 14pt \"Arial Unicode MS\";")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(150, 650, 161, 41))
        self.textBrowser_8.setStyleSheet("font: 14pt \"Arial Unicode MS\";")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(460, 650, 151, 41))
        self.textBrowser_9.setStyleSheet("font: 14pt \"Arial Unicode MS\";")
        self.textBrowser_9.setObjectName("textBrowser_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action103 = QtWidgets.QAction(MainWindow)
        self.action103.setObjectName("action103")
        self.pushButton.clicked.connect(self.openFile)
        self.pushButton_2.clicked.connect(self.show2D)
        self.pushButton_3.clicked.connect(self.button)
        self.pushButton_4.clicked.connect(self.showDialog1)
        self.pushButton_5.clicked.connect(self.show3D)
        self.pushButton_6.clicked.connect(self.show3D)
        self.pushButton_7.clicked.connect(self.Show3DResult)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def openFile(self):
        get_filename_path = QFileDialog.getExistingDirectory(None, "选取单个文件", "")
        self.textBrowser.setText(str(get_filename_path))

    def show2D(self):
        one = self.textBrowser.toPlainText()
        get_filename_path, ok = QFileDialog.getOpenFileName(None, "选取单个文件", one, "Open Files (*.nii.gz)")
        if ok:
            filepath1 = os.path.basename(get_filename_path)
            self.textBrowser_2.setText(str(filepath1))
            example_filename = str(get_filename_path)
            img = nib.load(example_filename)
            data = np.asarray(img.dataobj)
            window_center = 0  # 窗位
            window_width = 2000  # 窗宽
            self.lineEdit_2.setText(str(window_center))
            self.lineEdit_3.setText(str(window_width))
            win_min = (2 * window_center - window_width) / 2.0 + 0.5
            win_max = (2 * window_center + window_width) / 2.0 + 0.5
            data[data > win_max] = win_max
            data[data < win_min] = win_min
            data = (data - win_min) / (win_max - win_min)
            new_nifti = nib.Nifti1Image(data, img.affine)
            OrthoSlicer3D(new_nifti.dataobj).show()

    def button(self):
        one = self.textBrowser.toPlainText()
        if len(one)!=0:
            two = self.textBrowser_2.toPlainText()
            if len(two) != 0:
                example_filename = os.path.join(one, two)
                img = nib.load(example_filename)
                data = np.asarray(img.dataobj)
                level = int(self.lineEdit_2.text())
                width = int(self.lineEdit_3.text())
                window_center = level  # 窗位
                window_width = width # 窗宽
                win_min = (2 * window_center - window_width) / 2.0 + 0.5
                win_max = (2 * window_center + window_width) / 2.0 + 0.5
                data[data > win_max] = win_max
                data[data < win_min] = win_min
                data = (data - win_min) / (win_max - win_min)
                new_nifti = nib.Nifti1Image(data, img.affine)
                OrthoSlicer3D(new_nifti.dataobj).show()

    def showDialog1(self):
        self.textBrowser_3.setText('预测中，请等待...')
        self.thread_1 = Thread_1()  # 创建线程
        self.thread_1.start()  # 开始线程
        self.thread_1.show_time.connect(self.showTime)

    def showTime(self,time):
        self.textBrowser_3.setText(time)

    def show3D(self):
        self.thread_2 = Thread_2()  # 创建线程
        self.thread_2.start()  # 开始线程

    def Show3DResult(self):
        one = self.textBrowser.toPlainText()
        get_filename_path, ok = QFileDialog.getOpenFileName(None, "选取单个文件", one, "Open Files (*.nii.gz)")
        if ok:
            file_path = get_filename_path  # 输入文件夹路径
            filename = os.path.basename(get_filename_path)
            self.textBrowser_4.setText(filename)
            mask = [0, 1, 2, 3]
            for v in mask:
                nii = nb.load(file_path)
                img = nii.get_fdata()
                voxel_dims = (nii.header["pixdim"])[1:4]
                tmp = {}
                for k in mask:
                    tmp[k] = np.sum(img == k)
                voxel_volume = np.prod(voxel_dims)
                end = '%.5f' % (tmp[v] * voxel_volume)
                if v == 1:
                    a = float(end)
                    self.textBrowser_5.setText(str(end))
                if v == 2:
                    b = float(end)
                    self.textBrowser_6.setText(str(end))
                if v == 3:
                    c = float(end)
                    self.textBrowser_7.setText(str(end))
            end1 = a/(a+b+c)
            end1 = '%.7f' % (end1)
            self.textBrowser_8.setText(str(end1))
            if float(end1)>0.4:
                strT = '<span style=\" color: #00ff00;\">%s</span>' %('正常')
                self.textBrowser_9.setText("%s" %(strT))
            else:
                strT = '<span style=\" color: #ff0000;\">%s</span>' %('主动脉夹层')
                self.textBrowser_9.setText("%s" %(strT))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'仿宋@璵..籀.\'; font-size:18pt; font-weight:600;\">基于平扫CT对主动脉夹层进行预测和提示的辅助诊断系统</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "读取患者文件夹路径："))
        self.pushButton_2.setText(_translate("MainWindow", "显示平扫图像"))
        self.pushButton_3.setText(_translate("MainWindow", "确定"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">调整窗宽窗位：</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "窗宽："))
        self.label_4.setText(_translate("MainWindow", "窗位："))
        self.pushButton_4.setText(_translate("MainWindow", "开始预测"))
        self.pushButton_5.setText(_translate("MainWindow", "显示3D效果图"))
        self.pushButton_6.setText(_translate("MainWindow", "中止预测"))
        self.pushButton_7.setText(_translate("MainWindow", "导入预测结果"))
        self.label_5.setText(_translate("MainWindow", "名称："))
        self.label_6.setText(_translate("MainWindow", "文件名称："))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">结果显示：</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "  V1："))
        self.label_9.setText(_translate("MainWindow", "  V2："))
        self.label_10.setText(_translate("MainWindow", "  V3："))
        self.label_11.setText(_translate("MainWindow", "  V1/(V1+V2+V3)："))
        self.label_12.setText(_translate("MainWindow", "结论："))
        self.action103.setText(_translate("MainWindow", "103"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
